// --- EVENT DATA ---
export const EVENTS_DATA = [
  {
    id: 11,
    title: "Figma",
    category: "Coding",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://images.unsplash.com/photo-1606161290889-77950cfb67d3?q=80&w=1170&auto=format&fit=crop",
    desc: "Design bold, think creative, and let your Figma skills steal the spotlight.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Participants must bring their own laptops with Figma installed.",
      "Theme will be provided on the spot.",
      "Use of pre-made templates is not allowed.",
      "Submission must include the prototype link.",
      "Late submissions will not be accepted.",
    ],
    head: {
      name: "Ayesha Rahman",
      mobile: "+91 98740 12345",
      email: "ayesha.design@events.com",
    },
    coHead: {
      name: "Rohan Verma",
      mobile: "+91 98312 98765",
      email: "rohan.v@events.com",
    },
    prizes: "Top 3 designers receive certificates + premium UI kits.",
  },

  // 2 — Line Follower
  {
    id: 4,
    title: "Line Follower",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1589254047589-db4c14ad7779?q=80&w=1170&auto=format&fit=crop",
    desc: "Where precision meets speed — build the bot that follows the line flawlessly.",
    participationMode: "team",
    price: 0,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 4,
    rules: [
      "Bots must operate autonomously.",
      "Going off-track results in penalty.",
      "Only one retry allowed.",
      "External assistance is prohibited.",
      "Inspection is mandatory before participation.",
    ],
    head: {
      name: "Sourav Das",
      mobile: "+91 91234 55678",
      email: "sourav.robotech@events.com",
    },
    coHead: {
      name: "Nikita Sen",
      mobile: "+91 98040 22345",
      email: "nikita.s@events.com",
    },
    prizes: "Winners receive cash prize + robotics toolkit.",
  },

  // 3 — Photo Story
  {
    id: 17,
    title: "Photo Story",
    category: "Miscellaneous",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image: "",
    desc: "Tell a compelling story through a series of photographs.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Submit 5–10 photos forming a story.",
      "Only original photos allowed.",
      "Basic edits allowed; no AI-generated images.",
      "Theme announced on the spot.",
      "Submission before deadline is mandatory.",
    ],
    head: {
      name: "Mehul Gupta",
      mobile: "+91 90900 11001",
      email: "mehul.g@events.com",
    },
    coHead: {
      name: "Shreya Bose",
      mobile: "+91 98760 44321",
      email: "shreya.b@events.com",
    },
    prizes: "Winning story featured in college magazine.",
  },

  // 4 — Treasure Hunt
  {
    id: 19,
    title: "Treasure Hunt",
    category: "Miscellaneous",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image:
      "https://plus.unsplash.com/premium_photo-1661313651013-e1bee6b0e558?q=80&w=1170&auto=format&fit=crop",
    desc: "Decode the clues, chase the trail, and claim the treasure before anyone else.",
    participationMode: "team",
    price: 0,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 3,
    maxMembers: 5,
    rules: [
      "Follow the clue order strictly.",
      "No entering restricted areas.",
      "Tampering with props leads to disqualification.",
      "No internet searches allowed.",
      "Team reaching final location first wins.",
    ],
    head: {
      name: "Aditya Singh",
      mobile: "+91 90078 22112",
      email: "aditya.hunt@events.com",
    },
    coHead: {
      name: "Tanisha Roy",
      mobile: "+91 70012 56112",
      email: "tanisha.r@events.com",
    },
    prizes: "Exclusive campus merchandise.",
  },

  // 5 — Carrom
  {
    id: 15,
    title: "Carrom",
    category: "Indoor Game",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "Game Room",
    image:
      "https://images.unsplash.com/photo-1620741211956-32977c8973be?q=80&w=880&auto=format&fit=crop",
    desc: "Slide, strike, dominate — show your mastery on the carrom board.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Standard ICF rules apply.",
      "Knockout elimination format.",
      "Fouls will result in penalty points.",
      "Late arrival = walkover.",
      "Decision of referee is final.",
    ],
    head: {
      name: "Rahul Sen",
      mobile: "+91 77788 99112",
      email: "rahul.sports@events.com",
    },
    coHead: {
      name: "Priya Das",
      mobile: "+91 90990 11221",
      email: "priya.d@events.com",
    },
    prizes: "Medals + certificates.",
  },

  // 6 — Capture the Flag
  {
    id: 10,
    title: "Capture The Flag",
    category: "Coding",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image: "",
    desc: "Cybersecurity challenge where participants exploit vulnerabilities and capture hidden flags.",
    participationMode: "team",
    price: 0,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 2,
    maxMembers: 3,
    rules: [
      "No external WiFi devices allowed.",
      "Tools must be open-source.",
      "Flag sharing between teams is prohibited.",
      "Any attempt to attack event infrastructure = disqualification.",
      "Top score within time wins.",
    ],
    head: {
      name: "Arnav Roy",
      mobile: "+91 92920 33445",
      email: "arnav.cyber@events.com",
    },
    coHead: {
      name: "Simran Jain",
      mobile: "+91 91234 22091",
      email: "simran.j@events.com",
    },
    prizes: "Hacker badges + goodies.",
  },

  // 7 — Paintball
  {
    id: 21,
    title: "Paintball",
    category: "Miscellaneous",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "Outdoor Arena",
    image:
      "https://images.unsplash.com/photo-1614602355999-bc295cba75b5?q=80&w=764&auto=format&fit=crop",
    desc: "Run, dodge, fire — dominate the arena with every splatter shot.",
    participationMode: "team",
    price: 0,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 4,
    maxMembers: 5,
    rules: [
      "No removing safety gear.",
      "Hits anywhere on body count.",
      "Referee decisions are final.",
      "Physical contact is prohibited.",
      "Ammo limits must be respected.",
    ],
    head: {
      name: "Vikrant Singh",
      mobile: "+91 99880 11234",
      email: "vikrant.p@events.com",
    },
    coHead: {
      name: "Anushka Mehta",
      mobile: "+91 77660 22123",
      email: "anushka.m@events.com",
    },
    prizes: "Winning team receives medals + goodies.",
  },

  // 8 — Lap Race
  {
    id: 6,
    title: "Lap Race",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://plus.unsplash.com/premium_photo-1682124389443-faa964f770c9?q=80&w=1170&auto=format&fit=crop",
    desc: "Speed, control, precision — let your bot conquer the track.",
    participationMode: "team",
    price: 0,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 4,
    rules: [
      "Bot must complete laps without assistance.",
      "Track damage or tampering leads to disqualification.",
      "One repair timeout allowed.",
      "Fastest lap time wins.",
      "Bot inspection is mandatory.",
    ],
    head: {
      name: "Ritwik Sharma",
      mobile: "+91 88220 33411",
      email: "ritwik.race@events.com",
    },
    coHead: {
      name: "Sneha Ghosh",
      mobile: "+91 91110 22345",
      email: "sneha.g@events.com",
    },
    prizes: "Robotics kit + certificate.",
  },

  // 9 — E-Football
  {
    id: 13,
    title: "E-Football",
    category: "Gaming",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://images.unsplash.com/photo-1587368062478-e804f5e2a55a?q=80&w=1323&auto=format&fit=crop",
    desc: "Play smart, strike hard, and let your gameplay rewrite the scoreboard.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Standard game settings will be used.",
      "Knockout format.",
      "Controller configuration allowed before match.",
      "Pausing without permission results in penalty.",
      "Referee decision final.",
    ],
    head: {
      name: "Rohit Anand",
      mobile: "+91 90807 22312",
      email: "rohit.efootball@events.com",
    },
    coHead: {
      name: "Aditi Sen",
      mobile: "+91 77990 99887",
      email: "aditi.s@events.com",
    },
    prizes: "Gaming vouchers.",
  },

  // 10 — Model Display
  {
    id: 7,
    title: "Model Display",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1742239034927-0b4efe83ae5e?q=80&w=687&auto=format&fit=crop",
    desc: "Bring your model, break the norms, and flex your innovation.",
    participationMode: "team",
    price: 0,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 1,
    maxMembers: 3,
    rules: [
      "Models must be original.",
      "Any hazardous component must be declared.",
      "Judging based on innovation & practicality.",
      "Static and dynamic demo allowed.",
      "Setup time: 10 minutes.",
    ],
    head: {
      name: "Imran Ali",
      mobile: "+91 70055 44123",
      email: "imran.md@events.com",
    },
    coHead: {
      name: "Moushumi Kar",
      mobile: "+91 82099 11245",
      email: "moushumi.k@events.com",
    },
    prizes: "Innovation award + certificates.",
  },

  // 11 — Terranova
  {
    id: 3,
    title: "Terranova",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1000",
    desc: "Navigate the terrain and conquer the obstacles.",
    participationMode: "team",
    price: 0,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 4,
    rules: [
      "Bots must complete the obstacle course.",
      "Damaging props results in penalty.",
      "Wireless control allowed but within limits.",
      "Breakdown time is included in final timing.",
      "Judgement based on speed + stability.",
    ],
    head: {
      name: "Abhishek Nair",
      mobile: "+91 73377 99112",
      email: "abhishek.tnova@events.com",
    },
    coHead: {
      name: "Ritu Gupta",
      mobile: "+91 99887 11245",
      email: "ritu.g@events.com",
    },
    prizes: "Tech goodies + certificate.",
  },

  // 12 — Navin Vidyarthi
  {
    id: 1,
    title: "Navin Vidyarthi",
    category: "Miscellaneous",
    date: "Feb 26, 2025",
    time: "10:00 AM",
    venue: "Main Auditorium",
    image: "",
    desc: "A warm, energetic welcome event for freshers.",
    price: 0,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Only registered students allowed.",
      "Maintain decorum inside the auditorium.",
      "Photography allowed only in designated time.",
      "Entry closes 15 minutes after start.",
      "Follow organizers' instructions.",
    ],
    head: {
      name: "Sanjana Ghosh",
      mobile: "+91 88022 11991",
      email: "sanjana.nv@events.com",
    },
    coHead: {
      name: "Ayush Mondal",
      mobile: "+91 70122 55340",
      email: "ayush.m@events.com",
    },
    prizes: "No prizes — this is an inauguration ceremony.",
  },

  // 13 — Robo War (8 KG)
  {
    id: 2,
    title: "Robo War (8 kg)",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "10:00 AM",
    venue: "Open Air Theatre",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop",
    desc: "Clash of metal titans. Build your bot and battle for dominance.",
    participationMode: "team",
    price: 0,
    teamPrice: 300,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 5,
    rules: [
      "Weight limit: 8 KG max.",
      "Weapons allowed: spinning, wedges, flippers.",
      "No projectiles or liquid weapons.",
      "Safety checks mandatory.",
      "Last bot standing wins.",
    ],
    head: {
      name: "Arindam Paul",
      mobile: "+91 99001 23456",
      email: "arindam.war@events.com",
    },
    coHead: {
      name: "Nikita Rao",
      mobile: "+91 90112 45678",
      email: "nikita.r@events.com",
    },
    prizes: "Trophy + ₹5,000 cash.",
  },

  // 14 — Chess
  {
    id: 14,
    title: "Chess",
    category: "Indoor Game",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "Game Room",
    image:
      "https://images.unsplash.com/photo-1586165368502-1bad197a6461?q=80&w=1258&auto=format&fit=crop",
    desc: "Think deep, play sharp, and outsmart every move.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "FIDE rules apply.",
      "Rapid format: 10 minutes each.",
      "No takebacks allowed.",
      "Touch-move rule enforced.",
      "Mobile phones must be switched off.",
    ],
    head: {
      name: "Arka Chatterjee",
      mobile: "+91 88012 33455",
      email: "arka.chess@events.com",
    },
    coHead: {
      name: "Jasmine Dutta",
      mobile: "+91 99110 55432",
      email: "jasmine.d@events.com",
    },
    prizes: "Medals + certificates.",
  },

  // 15 — Tech Quiz
  {
    id: 20,
    title: "Tech Quiz",
    category: "Miscellaneous",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1172&auto=format&fit=crop",
    desc: "Think quick, geek smart — outscore the competition with pure tech brilliance.",
    participationMode: "both",
    price: 100,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 2,
    maxMembers: 2,
    rules: [
      "No internet devices allowed.",
      "Buzzer round penalties apply.",
      "Tie-breaker questions for equal scores.",
      "Questions cover CS + IT domain.",
      "Judge decision final.",
    ],
    head: {
      name: "Souvik Pal",
      mobile: "+91 98980 22431",
      email: "souvik.quiz@events.com",
    },
    coHead: {
      name: "Shristi Mishra",
      mobile: "+91 90020 77411",
      email: "shristi.m@events.com",
    },
    prizes: "Tech books + certificates.",
  },

  // 16 — Super Coder
  {
    id: 9,
    title: "Super Coder",
    category: "Coding",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://plus.unsplash.com/premium_photo-1678566154673-a728037f3f00?q=80&w=702&auto=format&fit=crop",
    desc: "Code hard, break limits, and outsmart every problem thrown your way.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Contest duration: 2 hours.",
      "Language support: C/C++/Java/Python.",
      "Internet strictly prohibited.",
      "Ranking based on accuracy + time.",
      "Plagiarism leads to instant ban.",
    ],
    head: {
      name: "Ravi Kumar",
      mobile: "+91 98765 55421",
      email: "ravi.supercoder@events.com",
    },
    coHead: {
      name: "Lina Chakraborty",
      mobile: "+91 99330 11221",
      email: "lina.c@events.com",
    },
    prizes: "Top coder trophy.",
  },

  // 17 — Robo Soccer
  {
    id: 5,
    title: "Robo Soccer",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1666193183124-3f27c7800370?q=80&w=1040&auto=format&fit=crop",
    desc: "Gear up your bot for the ultimate robotic kickoff — score, defend, dominate.",
    participationMode: "team",
    price: 0,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 4,
    rules: [
      "Only non-destructive bots allowed.",
      "Match time: 5 minutes.",
      "Maximum 2 bots per team.",
      "Damaging opponent bot leads to penalty.",
      "Referee decision final.",
    ],
    head: {
      name: "Koushik Das",
      mobile: "+91 77112 99441",
      email: "koushik.rs@events.com",
    },
    coHead: {
      name: "Trisha Sen",
      mobile: "+91 99112 44122",
      email: "trisha.s@events.com",
    },
    prizes: "Trophy + robotics kit.",
  },

  // 18 — Photography
  {
    id: 16,
    title: "Photography",
    category: "Miscellaneous",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image:
      "https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?q=80&w=687&auto=format&fit=crop",
    desc: "Capture the moment, frame the story, and let your lens speak louder than words.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Only DSLR/Mirrorless/Phone cameras allowed.",
      "No AI-generated pictures allowed.",
      "Theme announced at venue.",
      "Basic editing allowed.",
      "Submission must include RAW files on request.",
    ],
    head: {
      name: "Ankit Rawat",
      mobile: "+91 90901 22113",
      email: "ankit.photo@events.com",
    },
    coHead: {
      name: "Riya Saha",
      mobile: "+91 87000 99812",
      email: "riya.s@events.com",
    },
    prizes: "Campus photography feature + certificate.",
  },

  // 19 — Graffiti
  {
    id: 18,
    title: "Graffiti",
    category: "Miscellaneous",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image:
      "https://images.unsplash.com/photo-1487452066049-a710f7296400?q=80&w=1171&auto=format&fit=crop",
    desc: "Splash your style, own the wall, and let your art speak in bold colors.",
    participationMode: "team",
    price: 0,
    teamPrice: 300,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 3,
    rules: [
      "Only eco-friendly colors allowed.",
      "No offensive / political art.",
      "Time limit: 90 minutes.",
      "Bring your own supplies.",
      "Judgment based on creativity + theme.",
    ],
    head: {
      name: "Tanmay Paul",
      mobile: "+91 98755 11240",
      email: "tanmay.g@events.com",
    },
    coHead: {
      name: "Mina Sarkar",
      mobile: "+91 99331 77420",
      email: "mina.s@events.com",
    },
    prizes: "Winning graffiti will be displayed on campus wall.",
  },

  // 20 — Drone
  {
    id: 8,
    title: "Drone",
    category: "Robotics",
    date: "Feb 26, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1521405924368-64c5b84bec60?q=80&w=1074&auto=format&fit=crop",
    desc: "Take flight and let your drone rule the skies.",
    participationMode: "team",
    price: 0,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 4,
    rules: [
      "Drone must pass safety check.",
      "Flying outside track results in penalty.",
      "Crashes = elimination.",
      "FPV allowed but bring your own gear.",
      "Battery change only during pit-stop.",
    ],
    head: {
      name: "Aryan Jha",
      mobile: "+91 78000 22178",
      email: "aryan.drone@events.com",
    },
    coHead: {
      name: "Noor Alam",
      mobile: "+91 88290 43012",
      email: "noor.a@events.com",
    },
    prizes: "Drone accessories + certificate.",
  },

  // 21 — BGMI (Already given)
  {
    id: 12,
    title: "BGMI",
    category: "Gaming",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://images.unsplash.com/photo-1599399056366-e318f572dbba?q=80&w=1170&auto=format&fit=crop",
    desc: "Aim sharp, rush hard, and let your squad dominate the battleground.",
    participationMode: "both",
    price: 0,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 4,
    maxMembers: 4,
    rules: [
      "Register full squad before deadline.",
      "No hacks/mods allowed.",
      "Emulators prohibited.",
      "Report 30 mins before event.",
      "Organizer decision final.",
    ],
    head: {
      name: "Vikram Sharma",
      mobile: "+91 98765 43210",
      email: "vikram.s@events.com",
    },
    coHead: {
      name: "Priya Singh",
      mobile: "+91 87654 32109",
      email: "priya.s@events.com",
    },
    prizes: "Trophy + gaming merchandise.",
  },
];

// --- EVENT CATEGORIES---
export const EVENT_CATEGORIES = [
  "ALL",
  "CODING",
  "ROBOTICS",
  "GAMING",
  "INDOOR GAME",
  "MISCELLANEOUS",
];

// --- EVENT SLIDES ---
export const EVENT_SLIDES = [
  {
    id: 0,
    title: "GAMING",
    subtitle: "THE ARENA",
    category: "GAMING",
    desc: "Immerse yourself in 48 hours of non-stop competitive gaming. From Valorant to FIFA, prove your dominance.",
    color: "from-red-900 to-orange-900", // Warm tones
    accent: "text-red-400",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=2070",
    // icon: Gamepad2,
  },
  {
    id: 1,
    title: "ROBOTICS",
    subtitle: "STEEL CLASH",
    category: "ROBOTICS",
    desc: "Witness the sparks fly as 8kg bots battle for supremacy in our state-of-the-art combat arena.",
    color: "from-orange-900 to-amber-900",
    accent: "text-orange-400",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=2070",
    // icon: Bot,
  },
  {
    id: 2,
    title: "CODING",
    subtitle: "LOGIC LAB",
    category: "CODING",
    desc: "Think fast, code faster — only the sharpest minds survive the challenge.",
    color: "from-red-900 to-rose-900",
    accent: "text-rose-400",
    image:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2070",
    // icon: Terminal,
  },
  {
    id: 3,
    title: "INDOOR GAME",
    subtitle: "THE PLAYHOUSE",
    category: "INDOOR GAME",
    desc: "Classic games, sharp minds, and pure competition — from chess strategies to carrom precision, step in and outplay everyone.",
    color: "from-slate-900 to-gray-800",
    accent: "text-sky-400",
    image:
      "https://plus.unsplash.com/premium_photo-1723478555114-2bebac948a50?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    // icon: Trophy,
  },
  {
    id: 4,
    title: "MISC",
    subtitle: "FUSION HUB",
    title: "MISCELLANEOUS",
    desc: "A creative fusion of skill and fun — photography, graffiti, quizzes, treasure hunts, paintball and more, all under one vibrant zone.",
    color: "from-gray-900 to-slate-900",
    accent: "text-violet-400",
    image:
      "https://images.unsplash.com/photo-1557933488-c8daa2a5772c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    // icon: Sparkles,
  },
];

// --- TEAM DATA ---
export const TEAM_DATA = [
  {
    id: 1,
    name: "Aritra Chowdhury",
    dept: "Convenor",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=1000",
    level: "L5",
    bio: "Orchestrating the chaos. Arjun ensures all systems are nominal and teams are synchronized.",
  },
  {
    id: 2,
    name: "Arna Saha",
    dept: "Convenor",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Visual visionary. Rohan paints with pixels and dreams in vector graphics.",
  },
  {
    id: 3,
    name: "Zishan Khan Chowdhury",
    dept: "Convenor",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Visual visionary. Rohan paints with pixels and dreams in vector graphics.",
  },
  {
    id: 4,
    name: "Smarta Das",
    dept: "SPOC",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Logistics commander. Priya ensures assets are deployed precisely where needed.",
  },
  {
    id: 5,
    name: "Ankur Vaibhav",
    dept: "SPOC",
    img: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Code ninja. Alex maintains the digital gateway to the TechVerse.",
  },
  {
    id: 6,
    name: "Aniket Das",
    dept: "Student Coordinator",
    img: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Resource acquisition. Tara secures the funding that powers our reality.",
  },
  {
    id: 7,
    name: "Ramesh Biswas",
    dept: "Student Coordinator",
    img: "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Supply chain expert. Nothing moves without Dev knowing about it.",
  },
  {
    id: 8,
    name: "Debtanu Roy",
    dept: "Student Coordinator",
    img: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Signal booster. Zoya broadcasts our frequency to the farthest reaches.",
  },
  {
    id: 9,
    name: "Champak Kundu",
    dept: "Finance Advisor",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "User empathy module. Mike ensures the interface doesn't reject the human host.",
  },
  {
    id: 10,
    name: "Dewan Habib",
    dept: "Finance",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=1000",
    level: "L2",
    bio: "React specialist. Lisa weaves components into a seamless digital fabric.",
  },
  {
    id: 11,
    name: "Akash Dey",
    dept: "Finance",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=1000",
    level: "L5",
    bio: "Orchestrating the chaos. Arjun ensures all systems are nominal and teams are synchronized.",
  },
  {
    id: 12,
    name: "Rudrojyoti Manna",
    dept: "Management Coordinator",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Visual visionary. Rohan paints with pixels and dreams in vector graphics.",
  },
  {
    id: 13,
    name: "Satyam Kundu",
    dept: "Media Head",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Visual visionary. Rohan paints with pixels and dreams in vector graphics.",
  },
  {
    id: 14,
    name: "Subhradeep Dey",
    dept: "Marketing Head",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Logistics commander. Priya ensures assets are deployed precisely where needed.",
  },
  {
    id: 15,
    name: "Nanda Lal Das",
    dept: "Tech Advisor",
    img: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Code ninja. Alex maintains the digital gateway to the TechVerse.",
  },
  {
    id: 16,
    name: "Anurag Bhattacharjee",
    dept: "Tech Advisor",
    img: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Resource acquisition. Tara secures the funding that powers our reality.",
  },
  {
    id: 17,
    name: "Niladri Sarkar",
    dept: "Tech Team",
    img: "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Supply chain expert. Nothing moves without Dev knowing about it.",
  },
  {
    id: 18,
    name: "Arghya Chakraborty",
    dept: "Tech Team",
    img: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Signal booster. Zoya broadcasts our frequency to the farthest reaches.",
  },
  {
    id: 19,
    name: "Aikik Patra",
    dept: "Tech Team",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "User empathy module. Mike ensures the interface doesn't reject the human host.",
  },
  {
    id: 20,
    name: "Aritra Chattopadhyay",
    dept: "Tech Team",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=1000",
    level: "L2",
    bio: "React specialist. Lisa weaves components into a seamless digital fabric.",
  },
  {
    id: 21,
    name: "Anwesa Ghosh",
    dept: "Decoration Head",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=1000",
    level: "L2",
    bio: "React specialist. Lisa weaves components into a seamless digital fabric.",
  },
];
