// --- EVENTS ---
export const EVENTS = [
  // "FIGMA",
  // "GRAFFITI",
  // "DRONE",
  // "PAINTBALL",
  // "LAP RACE",
  // "NAVIN VIDYARTHI",

  //robotics
  "ROBO WAR (8 KG)",
  "ROBO WAR (15 KG)",
  "TERRANOVA",
  "LINE FOLLOWER",
  "MODEL VISION",
  "ROBO SOCCER",

  //coding
  "SUPER CODER",
  "CAPTURE THE FLAG",

  //gaming
  "DIGITAL KICKOFF",
  "BGMI",

  //indoor game
  "TECH ARENA CHESS",
  "CARROMACT",

  //miscellaneous
  "NARRATIVE LENS",
  "THE NEXUS TRANSMUTATION",
  "QUIZZARACT",
  "FRAME WAR",
];

// --- EVENT DATA ---
export const EVENTS_DATA = [
  // 1 — Robo War (8 KG) - updated fully
  {
    id: 2,
    title: "Robo War (8 kg)",
    category: "Robotics",
    date: "Mar 27, 2026",
    time: "10:00 AM",
    venue: "Open Air Theatre",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop",
    desc: "Build an 8 kg remote-controlled combat robot and battle it out in a tournament-style arena fight. Your goal — disable, immobilize, or outscore your opponent within 3 minutes to claim victory.",
    participationMode: "team",
    price: 0,
    teamPrice: 800,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 6,
    rules: [
      "Maximum robot weight is 8 kg (100g tolerance); all power sources must be on-board.",
      "Only wireless remote control is allowed with a minimum 4-channel frequency; a manual Emergency Stop (E-Stop) is mandatory.",
      "Power must be electrical only (max 36V DC) using sealed batteries like LiPo, Li-ion, or NiMH.",
      "Allowed weapons include Spinners, Flippers, Lifters, Hammers, and Cutters. No liquid projectiles, jammers, or entangling devices.",
      "A robot loses if immobilized for 10 seconds, thrown out of the arena, or outscored on aggression, control, and damage.",
      "A kill switch and weapon lock are mandatory; safety inspection is required before every match.",
      "Teams using pneumatics or hydraulics must submit a safety authorization letter signed by faculty during registration.",
    ],
    head: {
      name: "Tousif Azim",
      mobile: "+91 9609670201",
      email: "tousifw00431@gmail.com",
    },
    head: {
      name: "Sudipto Mondal",
      mobile: "+91 8902478956",
      email: "sudiptohwh2005@gmail.com ",
    },
    coHead: {
      name: "Srijita Biswas",
      mobile: "+91 9804784751",
      email: "shreejitabiswasvis@gmail.com",
    },
    prizes: "",
  },
  // 2 — Robo War (15 KG) - updated fully
  {
    id: 11,
    title: "Robo War (15 kg)",
    category: "Robotics",
    date: "Mar 27, 2026",
    time: "10:00 AM",
    venue: "Open Air Theatre",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop",
    desc: "Build a 15 kg remote-controlled combat robot and compete in a high-stakes tournament-style arena battle. Immobilize, disable, or outscore your opponent within 3 minutes to advance and claim victory.",
    participationMode: "team",
    price: 0,
    teamPrice: 1000,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 6,
    rules: [
      "Maximum robot weight is 15 kg (100g tolerance); all power sources must be on-board, and each bot in a cluster must have individual drive.",
      "Only wireless remote control is allowed with a minimum 4-channel frequency; a manual Emergency Stop (E-Stop) is mandatory.",
      "Power must be electrical only (max 36V DC) using sealed batteries like LiPo, Li-ion, or NiMH. No IC engines allowed.",
      "Allowed weapons include Spinners, Flippers, Lifters, Hammers, and Cutters. No liquid projectiles, RF jammers, or entangling devices.",
      "A robot loses if immobilized for 10 seconds, thrown out of the arena, or outscored on aggression, control, and damage.",
      "A kill switch and weapon lock are mandatory; safety inspection is required before every match.",
      "Teams using pneumatics or hydraulics must submit a safety authorization letter signed by faculty during registration.",
    ],
    head: {
      name: "Jeet pal ",
      mobile: "+91 7797303055",
      email: "jeet832004@gmail.com",
    },
    head: {
      name: "Soumodeep Guho",
      mobile: "+91 8967203175",
      email: "soumyadeepguha69@gmail.com",
    },
    coHead: {
      name: "Supriyo Mondal",
      mobile: "+91 9064457370",
      email: "",
    },
    prizes: "",
  },
  // 3 — Terranova - updated fully
  {
    id: 3,
    title: "Terranova",
    category: "Robotics",
    date: "Mar 27, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1000",
    desc: "Trapped in the abyss, your only hope is to break free by reaching the gates of heaven. The path is the ruthless “Hell Road,” where you must race at full speed, crash through dangers, and conquer every obstacle as fast as possible. Victory means escape — and peace at last.",
    participationMode: "team",
    price: 0,
    teamPrice: 300,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 5,
    rules: [
      "Bot Specifications:",
      "The dimension of the bot must be 25cm x 25cm x 25cm, including wheels (10% tolerance is allowed).",
      "The maximum weight of the bot is 3 kg.",
      "The wire must be 12ft long to avoid any issues.",
      "Ready-made toys/IC engines/LEGO kits are not allowed.",
      "Both wired and wireless controllers are allowed. In wireless RF controllers, Wi-Fi and",
      "Bluetooth-based controllers are also allowed.",

      "Rules:",
      "A team of a maximum of 5 members will be allowed to participate.",
      "Point systems will be introduced at the start of the event.",
      "Skip will incur a penalty of 30 seconds.",
      "Any hand touch will cause a penalty of 10 seconds for the hand touch.",
      "The bonus score will deduct 10 seconds.",
      "Timeout of 3 minutes.",
      "The maximum voltage used for driving the bot should be 24V.",
    ],
    head: {
      name: "Rudranil Goswami ",
      mobile: "+91 9830411863",
      email: "rudranilgoswami3@gmail.com",
    },
    coHead: {
      name: "Dhruba Biswas",
      mobile: "+91 8145104502",
      email: "dhrubabiswas159@gmail.com",
    },
    coHead: {
      name: "Samrat Sinha",
      mobile: "+91 8420112474",
      email: "ss4912817@gmail.com",
    },
    prizes: "",
  },
  // 4 — Line Follower - updated fully
  {
    id: 4,
    title: "Line Follower",
    category: "Robotics",
    date: "Mar 27, 2026",
    time: "11:00 AM Onwards",
    venue: "GNIT",
    image:
      "https://images.unsplash.com/photo-1589254047589-db4c14ad7779?q=80&w=1170&auto=format&fit=crop",
    desc: "Speed alone won't save you here. In this high-stakes time trial, your robot must navigate a twisting track of black lines on a white arena autonomously. From 90-degree turns to tricky crossovers, this event tests the stability of your hardware and the intelligence of your algorithms. Build it fast, code it smart, and don't lose the line!",
    participationMode: "both",
    price: 150,
    teamPrice: 200,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 4,
    rules: [
      "Build a fully autonomous line-following robot.",
      "Track includes sharp turns, acute angles, crossovers, and lighting variations.",
      "Robot must follow a black line on a white surface (or vice versa).",
      "No remote control allowed — fully self-operated after start.",
      "Uses sensor array to detect path and adjust motors in real-time.",
      "Must maintain accuracy even at high speed.",
      "Fastest robot to complete the track without derailing wins.",
    ],
    head: {
      name: "Anshuman Shaw",
      mobile: "+91 9088411976",
      email: "ansh98314414488@gmail.com",
    },
    coHead: {
      name: "Supratik Nath",
      mobile: "+91 9932237759",
      email: "supratik9832@gmail.com",
    },
    prizes: "",
  },
  // 5 — Model ViSION - updated fully
  {
    id: 7,
    title: "Model Vision",
    category: "Robotics",
    date: "Mar 27, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1742239034927-0b4efe83ae5e?q=80&w=687&auto=format&fit=crop",
    desc: "Welcome to Model Vision — where ideas come alive. Showcase your science, technology, engineering, and creative models that solve real-world problems. Let your innovation shine as you build, create, and inspire. Think beyond limits. Shape the future.",
    participationMode: "both",
    price: 80,
    teamPrice: 100,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 3,
    rules: [
      "For each group, there should be a maximum of 5 participants and a minimum of 1 participant.",
      "From each group 2 participants will be allowed to come forward and elaborate on the working and functioning of the model.",
      "The team leader of each group will have to register with proper details, and no entries will be entertained without registration.",
      "The judge's decision will be the final decision. ",
      "A proper uniform is mandatory for all team members. ",
      "Participants from GNIT should have their college ID cards with them. ",
      "Participants from other institutes or schools are requested to bring their institutional ID card.",
      "Every team must carry their own personal socket/extension board for model setup and power requirements. ",
      "Registration will be done on the website and at the registration desk before the event. ",
      "The event head's decision will be final, for under any circumstance's rules can be altered if needed by the organizing authority.",
    ],
    head: {
      name: "Manjeera Patra",
      mobile: "+91 8597757846",
      email: "manjeerapatra131602@gmail.com ",
    },
    coHead: {
      name: "Manjistha Patra",
      mobile: "+91 8597757874",
      email: "manjisthapatra1045@gmail.com ",
    },
    prizes: "",
  },
  // 6 — Robo Soccer -  updated fully
  {
    id: 5,
    title: "Robo Soccer",
    category: "Robotics",
    date: "Mar 27, 2026",
    time: "11:00 AM Onwards",
    venue: "Gaming Lab 1",
    image:
      "https://images.unsplash.com/photo-1666193183124-3f27c7800370?q=80&w=1040&auto=format&fit=crop",
    desc: "Step into the arena of warriors at Turbo-Kick! Tesseract 2k26 brings you the ultimate fusion of match-day energy and raw engineering. Build your custom bot to master the obstacle-laden Prelims and strike your way through adrenaline-pumping 1v1 Knockout battles. From the 6-minute eliminations to the 8-minute Grand Final, only the best strategies will survive the Golden Goal. Don't just watch the future of sports—build it. Register Now!",
    participationMode: "team",
    price: 0,
    teamPrice: 300,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 5,
    rules: [
      "🔹 Team Requirements",
      "Team size: 2–5 members",
      "Members can be from different institutions",
      "One participant → only one team",
      "Valid institutional ID mandatory",
      "No bot sharing between teams",
    ],
    head: {
      name: "Debjit mukherjee",
      mobile: "+91 9830464724",
      email: "mukh.debjit@gmail.com",
    },
    coHead: {
      name: "Rajdeep Das",
      mobile: "+91 9366141412",
      email: "rajdeepdas.india0@gmail.com",
    },
    prizes: "",
  },

  // 7 — Super Coder - updated fully
  {
    id: 9,
    title: "Super Coder",
    category: "Coding",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://plus.unsplash.com/premium_photo-1678566154673-a728037f3f00?q=80&w=702&auto=format&fit=crop",
    desc: "Code hard, break limits, and outsmart every problem thrown your way.",
    price: 100,
    teamPrice: 150,
    isTeamPriceFixed: true,
    participationMode: "both",
    minMembers: 1,
    maxMembers: 2,
    rules: [
      "A team can consist of at most 2 members.",
      "All coding languages are accepted.",
      "The program with the least characters (if applicable) or fastest correct submission wins.",
      "Pen drives, laptops, or any external digital devices are not allowed.",
      "Any participant found indulging in malpractice will be disqualified immediately.",
      "Copy-paste is allowed only within the code editor. Copying from external sources (extensions, internet, etc.) is strictly prohibited.",
      "Participants must be in proper uniform and must carry payment form and institutional ID cards.",
      "The decision of the Event Head will be final. The organizing authority reserves the right to modify rules if required.",
    ],
    head: {
      name: "Nazreen Imam",
      mobile: "+91 6206705516",
      email: "nazreenimam78601@gmail.com",
    },
    coHead: {
      name: "Gourav Chanda",
      mobile: "+91 9382757411",
      email: "gouravchandra935@gmail.com",
    },
    prizes: "",
  },
  // 8 — Capture the Flag - not updated
  {
    id: 10,
    title: "Capture The Flag",
    category: "Coding",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image: "",
    desc: "Cybersecurity challenge where participants exploit vulnerabilities and capture hidden flags.",
    participationMode: "team",
    price: 0,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 2,
    maxMembers: 3,
    rules: [
      "No external WiFi devices allowed.",
      "Tools must be open-source.",
      "Flag sharing between teams is prohibited.",
      "Any attempt to attack event infrastructure = disqualification.",
      "Top score within time wins.",
    ],
    head: {
      name: "Arnav Roy",
      mobile: "+91 92920 33445",
      email: "arnav.cyber@events.com",
    },
    coHead: {
      name: "Simran Jain",
      mobile: "+91 91234 22091",
      email: "simran.j@events.com",
    },
    prizes: "Hacker badges + goodies.",
  },

  // 9 — BGMI - not updated
  {
    id: 12,
    title: "BGMI",
    category: "Gaming",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://images.unsplash.com/photo-1599399056366-e318f572dbba?q=80&w=1170&auto=format&fit=crop",
    desc: "Aim sharp, rush hard, and let your squad dominate the battleground.",
    participationMode: "both",
    price: 0,
    teamPrice: 100,
    isTeamPriceFixed: false,
    minMembers: 4,
    maxMembers: 4,
    rules: [
      "Register full squad before deadline.",
      "No hacks/mods allowed.",
      "Emulators prohibited.",
      "Report 30 mins before event.",
      "Organizer decision final.",
    ],
    head: {
      name: "Vikram Sharma",
      mobile: "+91 98765 43210",
      email: "vikram.s@events.com",
    },
    coHead: {
      name: "Priya Singh",
      mobile: "+91 87654 32109",
      email: "priya.s@events.com",
    },
    prizes: "Trophy + gaming merchandise.",
  },
  // 10 — DIGITAL KICKOFF - not updated
  {
    id: 13,
    title: "DIGITAL KICKOFF",
    category: "Gaming",
    date: "Feb 26, 2026",
    time: "09:00 AM",
    venue: "CSE Lab",
    image:
      "https://images.unsplash.com/photo-1587368062478-e804f5e2a55a?q=80&w=1323&auto=format&fit=crop",
    desc: "Play smart, strike hard, and let your gameplay rewrite the scoreboard.",
    price: 0,
    teamPrice: 100,
    participationMode: "team",
    isTeamPriceFixed: true,
    minMembers: 3,
    maxMembers: 4,
    rules: [
      "Standard game settings will be used.",
      "Knockout format.",
      "Controller configuration allowed before match.",
      "Pausing without permission results in penalty.",
      "Referee decision final.",
    ],
    head: {
      name: "Rohit Anand",
      mobile: "+91 90807 22312",
      email: "rohit.efootball@events.com",
    },
    coHead: {
      name: "Aditi Sen",
      mobile: "+91 77990 99887",
      email: "aditi.s@events.com",
    },
    prizes: "Gaming vouchers.",
  },

  // 11 — Carromact - fully updated
  {
    id: 15,
    title: "Carromact",
    category: "Indoor Game",
    date: "Mar 27, 2026",
    time: "09:00 AM",
    venue: "Game Room",
    image:
      "https://images.unsplash.com/photo-1620741211956-32977c8973be?q=80&w=880&auto=format&fit=crop",
    desc: "Carrom is a game of elegance, control, and sharp judgment .At Tesseract Carromact 2K26, the board becomes the battlefield where strategy meets precision and patience turns into victory. What starts as a simple break will evolve into a gripping contest of calculated moves, defensive play, and decisive strikes. Players will face high-pressure situations that demand focus, accuracy, and discipline. With exciting matches, intense moments, and pure competitive energy, Carromact 2K26 invites you to showcase your skills and experience the thrill of professional-level carrom. Get ready to aim, strike, and conquer the board.",
    price: 100,
    teamPrice: 150,
    isTeamPriceFixed: true,
    participationMode: "both",
    minMembers: 2,
    maxMembers: 2,
    rules: [
      "🔹 Qualifier Round",
      "Conducted offline on college premises.",
      "Participants must report to the assigned venue (to be announced).",
      "Matches played in short-format based on standard carrom rules.",
      "Time limits & scoring pattern explained before start.",
      "Top performers/teams qualify for the Final Round.",

      "🔹 Final Round",
      "Conducted offline.",
      "Matches follow standard professional carrom rules.",
      "Detailed rules & format explained before matches begin.",
      "Participants must maintain discipline, fairness & sportsmanship.",
      "Winner and 1st Runner-up decided based on performance.",

      "🔹 Other Important Details",
      "Judge/organizing committee decision will be final.",
      "Any form of misconduct or unfair play will lead to disqualification.",
      "Participants must report on time for their matches.",
      "The organizing committee expects complete integrity from all players.",
    ],
    head: {
      name: "Somnath Bose",
      mobile: "+91 6290211630",
      email: "somnathbose0705@gmail.com",
    },
    coHead: {
      name: "Sayan Tagore",
      mobile: "+91 8420819573",
      email: "sayantagore85@gmail.com",
    },
    prizes: "",
  },
  // 12 — TECH ARENA Chess - fully updated
  {
    id: 14,
    title: "Tech Arena Chess",
    category: "Indoor Game",
    date: "Mar 27, 2026",
    time: "09:00 AM",
    venue: "Game Room",
    image:
      "https://images.unsplash.com/photo-1586165368502-1bad197a6461?q=80&w=1258&auto=format&fit=crop",
    desc: "Think deep, play sharp, and outsmart every move.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Players must register before the deadline through the official page or registration desk.",
      "Players must report on time, late arrival may lead to disqualification.",
      "Players are not required to carry any chess equipment.",
      "Exciting prizes for winners and e-certificates for all participants.",
      "For any issue, players should contact the organizers.",
      "The organizer’s decision will be final in case of any dispute during the event.",

      "Game Rules:",

      "The tournament will follow a knockout format conducted under standard FIDE chess rules.",
      "White moves first, and player colors will be decided by pairing.",
      "Time Control: Each game will be 10 minutes per player, and 15 minutes per player in the final round.",
      "If a player touches a piece, they must move it if the move is legal; otherwise, it is considered an illegal move.",
      "An illegal move counts only if the opponent claims it. After the claim, the position is restored, and after 3 illegal moves by a player, they will be disqualified.",
      "If 50 moves pass without a pawn move or capture, the game is drawn.",
      "In case of a draw, the winner will be decided by a 5-minute tiebreak game per player.",
      "If a player’s time runs out, they lose the game unless the opponent does not have sufficient material to checkmate.",
      "All standard rules including en-passant, castling, threefold repetition and pawn promotion are allowed.",
      "Spectators must not interfere or give advice.",
      "Mobile phones and electronic devices must be silent during a game.",
      "Players may resign at any time, but draws cannot be offered.",
      "Any unfair practice or misconduct may lead to disqualification.",
    ],
    head: {
      name: "Surajit Tunga",
      mobile: "+91 8972195682",
      email: "surajittunga2005@gmail.com",
    },
    coHead: {
      name: "Sayak Banerjee ",
      mobile: "+91 9874308654",
      email: "banerjeesayak377@gmail.com",
    },
    prizes: "",
  },

  // 13 — Narrative lens - fully updated
  {
    id: 17,
    title: "Narrative lens",
    category: "Miscellaneous",
    date: "Mar 28, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image: "",
    desc: "THIS EVENT CHALLENGES YOU TO BE A VISUAL STORYTELLER. INSTEAD OF SHOWING US JUST ONE POWERFUL IMAGE, YOU NEED TO USE A SMALL GROUP OF PICTURES THAT ALL FIT TOGETHER TO TELL A COMPLETE STORY, JOURNEY, OR IDEA.YOU MUST SUBMIT BETWEEN FOUR AND SIX PHOTOGRAPHS. THESE PICTURES CANNOT BE RANDOM; THEY MUST ALL FOCUS ON ONE SINGLE TOPIC AND BE PLACED IN A SPECIFIC ORDER SO THAT THE STORY FLOWS NATURALLY.THINK OF IT LIKE CREATING A SHORT MOVIE REEL WHERE EVERY FRAME IS IMPORTANT. THE MAIN GOAL IS TO MAKE SURE YOUR AUDIENCE CAN EASILY FOLLOW YOUR MESSAGE FROM THE VERY FIRST PICTURE TO THE VERY LAST ONE. THE ENTIRE SET MUST LOOK CONSISTENT AND CLEAR.",
    price: 250,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "THE SUBMISSION MUST BE A PHOTO ESSAY—A SERIES OF PHOTOGRAPHS THAT TELLS A SINGULAR, INTEGRATED STORY OR NARRATIVE.",
      "ENTRY WILL BE DISQUALIFIED IF THE ENTRY DOES NOT FOLLOW THE THEME. ",
      "THE SET MUST CONTAIN A MINIMUM OF 4 AND A MAXIMUM OF 6 INDIVIDUAL IMAGES. SUBMISSIONS OUTSIDE THIS RANGE WILL BE DISQUALIFIED",
      "MAXIMUM FILE SIZE OF [SUGGEST 5MB] PER IMAGE.",
      "ALL IMAGES MUST BE SUBMITTED IN HIGH-QUALITY JPEG (.JPG) FORMAT.",
      "THE PARTICIPANT MUST CLEARLY INDICATE THE INTENDED VIEWING SEQUENCE (E.G., BY NAMING FILES STORYNAME_01.JPG, STORYNAME_02.JPG, ETC.)",
      "THE PHOTOGRAPHS THEMSELVES MUST NOT CONTAIN ANY IDENTIFYING MARKS, BORDERS, LOGOS, OR WATERMARKS. THE FILE NAMES AND SUBMISSION FORM WILL BE USED FOR IDENTIFICATION.",
    ],
    head: {
      name: "Sholankee Saha",
      mobile: "+91 9475834338",
      email: "me.sholankee18@gmail.com ",
    },
    coHead: {
      name: "Subhankar Baur",
      mobile: "+91 7477772135",
      email: "",
    },
    prizes: "",
  },
  // 14 — The Nexus Transmutation - fully updated
  {
    id: 19,
    title: "The Nexus Transmutation",
    category: "Miscellaneous",
    date: "Mar 28, 2026",
    time: "09:00 AM",
    venue: "GNIT",
    image:
      "https://plus.unsplash.com/premium_photo-1661313651013-e1bee6b0e558?q=80&w=1170&auto=format&fit=crop",
    desc: "⚡The Nexus Transmutation, 25 minutes to shatter quantum ciphers, hijack AR geometry, and execute the perfect knowledge transfer.",

    participationMode: "team",

    // Pricing Logic
    price: 0,
    teamPrice: 200, // Default for 1–3 members
    isTeamPriceFixed: false,
    specialTeamPrice: {
      members: 4,
      price: 250,
    },

    minMembers: 2,
    maxMembers: 4,

    rules: [
      "⏳ Total time limit: 25 minutes (strictly enforced)",
      "👥 Maximum 4 participants per team",
      "🚫 No personal devices allowed (phones, laptops, smartwatches, etc.)",
      "🖥️ Only the provided Nexus Console can be used",
      "🌐 Challenges involve both digital and physical world elements",
      "🔐 Participants must solve advanced encryption and cipher-based tasks",
      "🧩 Clues may be hidden in augmented reality (AR) geometry",
      "⚖️ Final round includes a live, time-pressured academic search (Ethical Crucible)",
      "🚨 Extreme pressure environment — performance under stress matters",
      "🏆 Team completing all challenges successfully within time wins",
    ],

    head: {
      name: "Mahabir Mahato",
      mobile: "+91 9163934535",
      email: "mahabirmahatha2003@gmail.com",
    },

    coHead: {
      name: "Swaraj Dhara",
      mobile: "+91 9477776150",
      email: "swarajdhara47@gmail.com",
    },

    subHead: {
      name: "Ananya Kar",
      mobile: "+91 8637886583",
      email: "",
    },

    prizes: "",
  },
  // 15 — Quizzaract - fully updated
  {
    id: 20,
    title: "Quizzaract",
    category: "Miscellaneous",
    date: "Mar 28, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1172&auto=format&fit=crop",
    desc: "In 1964, the first computer mouse wasn’t plastic, wireless, or RGB  it was a wooden block with wheels. At Tesseract Quizzaract 2K26, the only wooden thing will be the stage… but the ideas will shine with silicon grade sharpness. What will begin as a simple quiz will turn into a high voltage showdown of logic, code, and creativity where every cracked answer will feel like reinventing the mouse all over again.From mind bending logic traps to rapid fire tech rounds, teams will not just answer questions they will debug their own limits and leave the crowd buzzing for more. The event will promise a rollercoaster of intellect, excitement, and some truly epic ‘Aha!’ moments. Are you ready to geek out and test your tech-savvy skills? Our tech quiz is here to challenge your knowledge. Get ready to level up your tech IQ and see if you have what it takes to be a tech genius. So, get ready to test your tech intelligence! and let's dive into the exciting world of technology!",
    participationMode: "both",
    price: 100,
    teamPrice: 150,
    isTeamPriceFixed: true,
    minMembers: 2,
    maxMembers: 2,
    rules: [
      "Qualifier round:",
      "This round will be conducted through google forms in online mode. All the participants should come to the college premises (The room number will be declared later)",
      "In the Google form, there will be 22 Questions in total, (among them 20 questions are mandatory and in MCQ format + 2 questions are optional and in SAQ format)",
      "The total allotted time for Prelims is 15 minutes.",
      "Depending upon the participation top teams will be eligible for the Final round.",

      "Final round:",
      "This round will be conducted in offline mode. Participants will be provided a paper and would have to write answers on it",
      "Rules and further information about this round will be provided on the spot",
      "Participants are requested to write their team's name, the team leader's name, a valid phone number, and the team leader's Email-Id on top of the paper",
      "Based on the performance, the WINNER TEAM and 1st Runner up team will be decided. We expect proper integrity from your end.",
    ],
    head: {
      name: "Nowrin Parveen ",
      mobile: "+91 8373015328",
      email: "nowrinparveen365@gmail.com",
    },
    coHead: {
      name: "Badhan Majumder",
      mobile: "+91 6290677652",
      email: "badhanmozumder04@gmail.com ",
    },
    prizes: "",
  },
  // 16 — Frame War - fully updated
  {
    id: 16,
    title: "Frame War",
    category: "Miscellaneous",
    date: "Mar 28, 2026",
    time: "09:00 AM",
    venue: "XY Room",
    image:
      "https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?q=80&w=687&auto=format&fit=crop",
    desc: "Capture the moment, frame the story, and let your lens speak louder than words.",
    price: 100,
    participationMode: "solo",
    minMembers: 1,
    maxMembers: 1,
    rules: [
      "Only DSLR/Mirrorless/Phone cameras allowed.",
      "No AI-generated pictures allowed.",
      "Theme announced at venue.",
      "Basic editing allowed.",
      "Submission must include RAW files on request.",
    ],
    head: {
      name: "Arnabi Ghosh",
      mobile: "+91 8240251631",
      email: "arnabighosh2305@gmail.com",
    },
    coHead: {
      name: "Riya Singha Roy",
      mobile: "+91 9064632245",
      email: "riyasinharoy02@gmail.com",
    },
    prizes: "",
  },
];

// --- EVENT CATEGORIES---
export const EVENT_CATEGORIES = [
  "ALL",
  "CODING",
  "ROBOTICS",
  "GAMING",
  "INDOOR GAME",
  "MISCELLANEOUS",
];

// --- EVENT SLIDES ---
export const EVENT_SLIDES = [
  {
    id: 0,
    title: "GAMING",
    subtitle: "THE ARENA",
    category: "GAMING",
    desc: "Immerse yourself in 48 hours of non-stop competitive gaming. From Valorant to FIFA, prove your dominance.",
    color: "from-red-900 to-orange-900", // Warm tones
    accent: "text-red-400",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=2070",
    // icon: Gamepad2,
  },
  {
    id: 1,
    title: "ROBOTICS",
    subtitle: "STEEL CLASH",
    category: "ROBOTICS",
    desc: "Witness the sparks fly as 8kg bots battle for supremacy in our state-of-the-art combat arena.",
    color: "from-orange-900 to-amber-900",
    accent: "text-orange-400",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=2070",
    // icon: Bot,
  },
  {
    id: 2,
    title: "CODING",
    subtitle: "LOGIC LAB",
    category: "CODING",
    desc: "Think fast, code faster — only the sharpest minds survive the challenge.",
    color: "from-red-900 to-rose-900",
    accent: "text-rose-400",
    image:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2070",
    // icon: Terminal,
  },
  {
    id: 3,
    title: "INDOOR GAME",
    subtitle: "THE PLAYHOUSE",
    category: "INDOOR GAME",
    desc: "Classic games, sharp minds, and pure competition — from chess strategies to carrom precision, step in and outplay everyone.",
    color: "from-slate-900 to-gray-800",
    accent: "text-sky-400",
    image:
      "https://plus.unsplash.com/premium_photo-1723478555114-2bebac948a50?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    // icon: Trophy,
  },
  {
    id: 4,
    title: "MISC",
    subtitle: "FUSION HUB",
    title: "MISCELLANEOUS",
    desc: "A creative fusion of skill and fun — photography, graffiti, quizzes, treasure hunts, paintball and more, all under one vibrant zone.",
    color: "from-gray-900 to-slate-900",
    accent: "text-violet-400",
    image:
      "https://images.unsplash.com/photo-1557933488-c8daa2a5772c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    // icon: Sparkles,
  },
];

// --- TEAM DATA ---
export const TEAM_DATA = [
  {
    id: 1,
    name: "Arna Saha",
    dept: "Convenor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710652/tesseract/core_team/arna_saha.jpg",
    level: "L4",
    bio: "Strategic leader driving vision, coordination, and execution across all teams.",
    email: "arnasaha098@gmail.com",
    github: "",
    linkedin: "http://www.linkedin.com/in/arna-saha-838330286",
    instagram: "https://www.instagram.com/vntnsh?igsh=MWZ3Z2lpNTFjcTk0aA==",
  },

  {
    id: 2,
    name: "Ramesh Biswas",
    dept: "Convenor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710663/tesseract/core_team/ramesh_biswas.jpg",
    level: "L3",
    bio: "Ensures seamless collaboration and leads the organization toward impactful outcomes.",
    email: "rameshbiswas855277@gmail.com",
    github: "",
    linkedin:
      "https://www.linkedin.com/in/ramesh-biswas-4710652aa?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    instagram:
      "https://www.instagram.com/rudra_26082?igsh=N3Z4dTJwNTdmYXFk&utm_source=qr",
  },

  {
    id: 3,
    name: "Debtanu Roy",
    dept: "Co-convenor",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Supports core leadership and streamlines operations for smooth event execution.",
    email: "debtanuroy82@gmail.com",
    github: "",
    linkedin: "https://www.linkedin.com/in/debtanu-roy-0a15792a9",
    instagram: "https://www.instagram.com/dr_roy.jpg",
  },

  {
    id: 4,
    name: "Rudrojyoti Manna",
    dept: "Co-convenor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710665/tesseract/core_team/rudrojyoti_manna.jpg",
    level: "L4",
    bio: "Bridges strategy and implementation while managing team coordination.",
    email: "mannarudro05@gmail.com",
    github: "",
    linkedin:
      "https://www.linkedin.com/in/rudrojyotimanna?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    instagram:
      "https://www.instagram.com/literally_insane_05?igsh=bmlweXY0cDlpYWth",
  },

  {
    id: 5,
    name: "Swarnabindu Sen",
    dept: "SPOC",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Primary point of contact ensuring clear communication and efficient coordination.",
    email: "",
    github: "",
    linkedin: "",
    instagram: "",
  },

  {
    id: 6,
    name: "Dewan Habib",
    dept: "Finance",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710662/tesseract/core_team/dewan_habib.jpg",
    level: "L2",
    bio: "Manages budgets and financial planning to ensure sustainable growth.",
    email: "dewanhabib2004@gmail.com",
    github: "",
    linkedin:
      "https://www.linkedin.com/in/dewan-habib-701a5b320?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram: "https://www.instagram.com/the1_habib?igsh=MTgydTdpczJvaTZ3bA==",
  },

  {
    id: 7,
    name: "Akash Dey",
    dept: "Finance",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710684/tesseract/core_team/akash_dey.jpg",
    level: "L5",
    bio: "Oversees fund allocation and maintains transparent financial operations.",
    email: "deyakash2525@gmail.com",
    github: "",
    linkedin: "https://www.linkedin.com/in/akash-dey-a5291930b/",
    instagram: "https://www.instagram.com/akash.dey__18?igsh=YTEwa254NHVld21w",
  },

  {
    id: 8,
    name: "Satyam Kundu",
    dept: "Media Head",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710679/tesseract/core_team/satyam_kundu.jpg",
    level: "L4",
    bio: "Leads creative storytelling and digital presence through impactful media strategies.",
    email: "satyamkundu77@gmail.com",
    github: "",
    linkedin:
      "https://www.linkedin.com/in/satyam-kundu-238b19289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram:
      "https://www.instagram.com/_s_a_t.y_a_m_?igsh=MXVxZWVuMzg2OWVzeQ==",
  },

  {
    id: 9,
    name: "Sneha Sen",
    dept: "Marketing Head",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L4",
    bio: "Drives branding, outreach, and engagement to maximize visibility and impact.",
    email: "",
    github: "",
    linkedin: "",
    instagram: "",
  },

  {
    id: 10,
    name: "Surajit Pal",
    dept: "Robotics Coordinator",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Guides robotics initiatives and fosters innovation in automation and hardware.",
    email: "",
    github: "",
    linkedin: "",
    instagram: "",
  },

  {
    id: 11,
    name: "Saksham Singh",
    dept: "Management Coordinator",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Organizes operations and ensures smooth execution of planning and logistics.",
    email: "",
    github: "",
    linkedin: "",
    instagram: "",
  },

  {
    id: 12,
    name: "Niladri Sarkar",
    dept: "Tech Team",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Builds scalable technical solutions and powers digital innovation.",
    email: "niladrisarkar422@gmail.com",
    github: "https://github.com/NiladriSarkar01",
    linkedin: "https://www.linkedin.com/in/niladri-sarkar-b96a40274/",
    instagram: "https://www.instagram.com/_nil_d_sarkar_/",
  },
  {
    id: 13,
    name: "Arghya Chakraborty",
    dept: "Tech Team",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710666/tesseract/core_team/arghya_chakraborty.jpg",
    level: "L3",
    bio: "Develops intelligent systems and contributes to cutting-edge technical projects.",
    email: "chakrabortyarghya11@gmail.com",
    github: "",
    linkedin:
      "https://www.linkedin.com/in/arghya-chakraborty-61b151276?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    instagram:
      "https://www.instagram.com/arghya_143_?igsh=MTd4aXhtczA5bThkag==",
  },
  {
    id: 14,
    name: "Aikik Patra",
    dept: "Tech Team",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "Collaborates on development tasks and enhances system performance.",
    email: "",
    github: "",
    linkedin: "https://www.linkedin.com/in/niladri-sarkar-b96a40274/",
    instagram: "https://www.instagram.com/_nil_d_sarkar_/",
  },
  {
    id: 15,
    name: "Aritra Chattopadhyay",
    dept: "Tech Team",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710652/tesseract/core_team/aritra_chattopadhyay.jpg",
    level: "L2",
    bio: "Transforms ideas into functional, user-friendly digital solutions.",
    email: "aritrachattopadhyay900@gmail.com",
    github: "",
    linkedin:
      "https://www.linkedin.com/in/aritra-chattopadhyay-5198492a4?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    instagram:
      "https://www.instagram.com/its_da_hooman?igsh=MWxpczc1dGN2c29oNQ==",
  },

  {
    id: 16,
    name: "Anwesa Ghosh",
    dept: "Decoration Head",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710666/tesseract/core_team/anwesa_ghosh.jpg",
    level: "L2",
    bio: "Designs immersive environments that elevate event aesthetics and experience.",
    email: "anwesa310@gmail.com",
    github: "",
    linkedin: "https://www.linkedin.com/in/anwesa-ghosh-472b29319/",
    instagram:
      "https://www.instagram.com/itz.annie7_?igsh=MTA4eGszd2lheGp0NQ==",
  },

  {
    id: 17,
    name: "Aritra Chowdhury",
    dept: "Advisor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710652/tesseract/core_team/aritra_chowdhury.jpg",
    level: "L5",
    bio: "Provides strategic guidance and mentorship to strengthen team direction.",
    email: "chowdhuryaritra215@gmail.com",
    github: "",
    linkedin: "http://www.linkedin.com/in/aritra-chowdhury-415055327",
    instagram: "https://www.instagram.com/aritra1452?igsh=MTVsZWptcG1jYm42OA==",
  },

  {
    id: 18,
    name: "Zishan Khan Chowdhury",
    dept: "Advisor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710696/tesseract/core_team/zishan_khan.jpg",
    level: "L4",
    bio: "Offers experienced insights to support decision-making and growth.",
    email: "zishankhan360@gmail.com",
    github: "",
    linkedin: "http://linkedin.com/in/zishan-khan-chowdhury-115607245",
  },

  {
    id: 19,
    name: "Smarta Das",
    dept: "Advisor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710680/tesseract/core_team/smarta_das.jpg",
    level: "L4",
    bio: "Guides long-term planning and ensures alignment with organizational goals.",
    email: "smartadas211@gmail.com",
    github: "",
    linkedin: "https://www.linkedin.com/in/smarta-das-63ab8b253",
    instagram: "https://www.instagram.com/smarta_2113?igsh=Z2Z6amRvMnJwbmdv",
  },

  {
    id: 20,
    name: "Champak Kundu",
    dept: "Advisor",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1000",
    level: "L3",
    bio: "upports leadership with valuable advice and operational perspective.",
    email: "",
    github: "",
    linkedin: "",
    instagram: "",
  },

  {
    id: 21,
    name: "Nanda Lal Das",
    dept: "Advisor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710665/tesseract/core_team/nanda.jpg",
    level: "L3",
    bio: "Mentors teams and contributes strategic oversight for sustainable progress.",
    email: "tikludas01@gmail.com",
    github: "",
    linkedin: "https://www.linkedin.com/in/nanda-das-7b2242243/",
    instagram: "https://www.instagram.com/heavenly_demon_dx/",
  },

  {
    id: 22,
    name: "Anurag Bhattacharjee",
    dept: "Advisor",
    img: "https://res.cloudinary.com/dtvxydxiv/image/upload/v1769710649/tesseract/core_team/anurag_bhattacharjee.jpg",
    level: "L3",
    bio: "Provides expert recommendations to enhance performance and innovation.",
    email: "",
    github: "",
    linkedin: "",
    instagram: "",
  },
];

//removed events
//1 - FIGMA
// {
//     id: 11,
//     title: "Figma",
//     category: "Coding",
//     date: "Feb 26, 2026",
//     time: "09:00 AM",
//     venue: "CSE Lab",
//     image:
//       "https://images.unsplash.com/photo-1606161290889-77950cfb67d3?q=80&w=1170&auto=format&fit=crop",
//     desc: "Design bold, think creative, and let your Figma skills steal the spotlight.",
//     price: 100,
//     participationMode: "solo",
//     minMembers: 1,
//     maxMembers: 1,
//     rules: [
//       "Participants must bring their own laptops with Figma installed.",
//       "Theme will be provided on the spot.",
//       "Use of pre-made templates is not allowed.",
//       "Submission must include the prototype link.",
//       "Late submissions will not be accepted.",
//     ],
//     head: {
//       name: "Ayesha Rahman",
//       mobile: "+91 98740 12345",
//       email: "ayesha.design@events.com",
//     },
//     coHead: {
//       name: "Rohan Verma",
//       mobile: "+91 98312 98765",
//       email: "rohan.v@events.com",
//     },
//     prizes: "Top 3 designers receive certificates + premium UI kits.",
//   },

// 7 — Paintball
// {
//   id: 21,
//   title: "Paintball",
//   category: "Miscellaneous",
//   date: "Feb 26, 2026",
//   time: "09:00 AM",
//   venue: "Outdoor Arena",
//   image:
//     "https://images.unsplash.com/photo-1614602355999-bc295cba75b5?q=80&w=764&auto=format&fit=crop",
//   desc: "Run, dodge, fire — dominate the arena with every splatter shot.",
//   participationMode: "team",
//   price: 0,
//   teamPrice: 100,
//   isTeamPriceFixed: false,
//   minMembers: 4,
//   maxMembers: 5,
//   rules: [
//     "No removing safety gear.",
//     "Hits anywhere on body count.",
//     "Referee decisions are final.",
//     "Physical contact is prohibited.",
//     "Ammo limits must be respected.",
//   ],
//   head: {
//     name: "Vikrant Singh",
//     mobile: "+91 99880 11234",
//     email: "vikrant.p@events.com",
//   },
//   coHead: {
//     name: "Anushka Mehta",
//     mobile: "+91 77660 22123",
//     email: "anushka.m@events.com",
//   },
//   prizes: "Winning team receives medals + goodies.",
// },

// // 8 — Lap Race
// {
//   id: 6,
//   title: "Lap Race",
//   category: "Robotics",
//   date: "Feb 26, 2026",
//   time: "11:00 AM Onwards",
//   venue: "Gaming Lab 1",
//   image:
//     "https://plus.unsplash.com/premium_photo-1682124389443-faa964f770c9?q=80&w=1170&auto=format&fit=crop",
//   desc: "Speed, control, precision — let your bot conquer the track.",
//   participationMode: "team",
//   price: 0,
//   teamPrice: 150,
//   isTeamPriceFixed: true,
//   minMembers: 2,
//   maxMembers: 4,
//   rules: [
//     "Bot must complete laps without assistance.",
//     "Track damage or tampering leads to disqualification.",
//     "One repair timeout allowed.",
//     "Fastest lap time wins.",
//     "Bot inspection is mandatory.",
//   ],
//   head: {
//     name: "Ritwik Sharma",
//     mobile: "+91 88220 33411",
//     email: "ritwik.race@events.com",
//   },
//   coHead: {
//     name: "Sneha Ghosh",
//     mobile: "+91 91110 22345",
//     email: "sneha.g@events.com",
//   },
//   prizes: "Robotics kit + certificate.",
// },

// 12 — Navin Vidyarthi
// {
//   id: 1,
//   title: "Navin Vidyarthi",
//   category: "Miscellaneous",
//   date: "Feb 26, 2025",
//   time: "10:00 AM",
//   venue: "Main Auditorium",
//   image: "",
//   desc: "A warm, energetic welcome event for freshers.",
//   price: 0,
//   participationMode: "solo",
//   minMembers: 1,
//   maxMembers: 1,
//   rules: [
//     "Only registered students allowed.",
//     "Maintain decorum inside the auditorium.",
//     "Photography allowed only in designated time.",
//     "Entry closes 15 minutes after start.",
//     "Follow organizers' instructions.",
//   ],
//   head: {
//     name: "Sanjana Ghosh",
//     mobile: "+91 88022 11991",
//     email: "sanjana.nv@events.com",
//   },
//   coHead: {
//     name: "Ayush Mondal",
//     mobile: "+91 70122 55340",
//     email: "ayush.m@events.com",
//   },
//   prizes: "No prizes — this is an inauguration ceremony.",
// },

// 19 — Graffiti
// {
//   id: 18,
//   title: "Graffiti",
//   category: "Miscellaneous",
//   date: "Feb 26, 2026",
//   time: "09:00 AM",
//   venue: "XY Room",
//   image:
//     "https://images.unsplash.com/photo-1487452066049-a710f7296400?q=80&w=1171&auto=format&fit=crop",
//   desc: "Splash your style, own the wall, and let your art speak in bold colors.",
//   participationMode: "team",
//   price: 0,
//   teamPrice: 300,
//   isTeamPriceFixed: true,
//   minMembers: 2,
//   maxMembers: 3,
//   rules: [
//     "Only eco-friendly colors allowed.",
//     "No offensive / political art.",
//     "Time limit: 90 minutes.",
//     "Bring your own supplies.",
//     "Judgment based on creativity + theme.",
//   ],
//   head: {
//     name: "Tanmay Paul",
//     mobile: "+91 98755 11240",
//     email: "tanmay.g@events.com",
//   },
//   coHead: {
//     name: "Mina Sarkar",
//     mobile: "+91 99331 77420",
//     email: "mina.s@events.com",
//   },
//   prizes: "Winning graffiti will be displayed on campus wall.",
// },

// // 20 — Drone
// {
//   id: 8,
//   title: "Drone",
//   category: "Robotics",
//   date: "Feb 26, 2026",
//   time: "11:00 AM Onwards",
//   venue: "Gaming Lab 1",
//   image:
//     "https://images.unsplash.com/photo-1521405924368-64c5b84bec60?q=80&w=1074&auto=format&fit=crop",
//   desc: "Take flight and let your drone rule the skies.",
//   participationMode: "team",
//   price: 0,
//   teamPrice: 150,
//   isTeamPriceFixed: true,
//   minMembers: 2,
//   maxMembers: 4,
//   rules: [
//     "Drone must pass safety check.",
//     "Flying outside track results in penalty.",
//     "Crashes = elimination.",
//     "FPV allowed but bring your own gear.",
//     "Battery change only during pit-stop.",
//   ],
//   head: {
//     name: "Aryan Jha",
//     mobile: "+91 78000 22178",
//     email: "aryan.drone@events.com",
//   },
//   coHead: {
//     name: "Noor Alam",
//     mobile: "+91 88290 43012",
//     email: "noor.a@events.com",
//   },
//   prizes: "Drone accessories + certificate.",
// },
